artifact_uri: file:///Users/dinisisaev/Desktop/laia/.mlruns/314449792163289134/ae61f4876e5a4cb4a7dcc6a22aea5452/artifacts
end_time: 1765665475252
entry_point_name: ''
experiment_id: '314449792163289134'
lifecycle_stage: active
run_id: ae61f4876e5a4cb4a7dcc6a22aea5452
run_name: trusting-midge-426
source_name: ''
source_type: 4
source_version: ''
start_time: 1765665409845
status: 4
tags: []
user_id: dinisisaev
