creation_timestamp: 1765665942846
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1765665942846
model_id: m-7d4825b6f85842eeb8c2e970ed505b8e
name: model
run_id: 3d207d35f3254e43ba93edf0fafb8c60
run_link: null
source: models:/m-7d4825b6f85842eeb8c2e970ed505b8e
status: READY
status_message: null
storage_location: file:///Users/dinisisaev/Desktop/laia/.mlruns/314449792163289134/models/m-7d4825b6f85842eeb8c2e970ed505b8e/artifacts
user_id: null
version: 1
