artifact_uri: /Users/dinisisaev/Desktop/laia/127.0.0.1/657105702710152706/ae636f03f03f47adb34a6ed60efacc71/artifacts
end_time: null
entry_point_name: ''
experiment_id: '657105702710152706'
lifecycle_stage: active
run_id: ae636f03f03f47adb34a6ed60efacc71
run_name: invincible-cow-663
source_name: ''
source_type: 4
source_version: ''
start_time: 1765666809661
status: 1
tags: []
user_id: dinisisaev
